services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    links:
      - "backend"
      - "adminer"
      - "frontend"
    environment:
      - TZ=${TZ}
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    expose:
      - 8080
  backend:
    image: magm3333/tomcat-jdk21:10.1.44
    container_name: backend
    restart: always
    environment:
      - TZ=${TZ}
      - ALARM_MAIL_TO=bmacedo197@alumnos.iua.edu.ar
      - SMTP_USER=bmacedo197@alumnos.iua.edu.ar
      - SMTP_PASS=sqqssqolrvwqlqcz
    depends_on: 
      - mysql
    expose:
      - 8080
    volumes:
      - ./tomcat/webapps:/opt/tomcat/webapps
      - ./tomcat/conf/catalina.properties:/opt/tomcat/conf/catalina.properties
      - ./tomcat/bin/setenv.sh:/opt/tomcat/bin/setenv.sh
      - /etc/localtime:/etc/localtime:ro

  frontend:
    build: 
      context: ./frontendvue # <--- AjustÃ¡ esta ruta relativa al compose
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    expose:
      - 80
    networks:
      - default # Esto permite que el Nginx principal lo vea por nombre

  mysql:
    image: mysql:8.0.43
    container_name: mysql_iw3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPWD}
      - MYSQL_USER=iw3
      - MYSQL_PASSWORD=${MYSQLPWD}
      - MYSQL_DATABASE=proyectofinalweb3
      - TZ=${TZ}
    expose:
      - 3306
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./mysqlinit:/docker-entrypoint-initdb.d
volumes: 
  mysql-data:

